// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderProcessing;

#nullable disable

namespace OrderProcessing.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("OrderProcessing.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ConvertedOrder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("converted_order");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_number");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("order_status");

                    b.Property<string>("SourceOrder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_order");

                    b.Property<int>("SystemType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("system_type");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
